branches:
  only:
    - master
matrix:
  include:
  - name: Android Build
    language: android
    jdk: openjdk8
    android:
      components:
      - build-tools-28.0.3
      - android-28
    before_script:
    - cd flutter
    - openssl aes-256-cbc -K $encrypted_799987a421b6_key -iv $encrypted_799987a421b6_iv 
      -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - if [ ! -d "flutter" ] ; then git clone https://github.com/flutter/flutter.git -b stable; fi;
    - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
    - gem install bundler && cd android && bundle install && cd ..
    script:
    - flutter packages get
    - flutter pub run flutter_launcher_icons:main
    - flutter test
    - build_number="$(git rev-list --count master)"
    - flutter build apk --build-number=$build_number
    - cd android && bundle exec fastlane alpha
    cache:
      bundler: true
      directories:
      - "$HOME/.pub-cache"
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
      - "$HOME/.android/build-cache"
      - "$HOME/flutter"
  exclude:
  - name: iOS Build
    os: osx
    language: generic
    osx_image: xcode10.2
    before_script:
    - cd flutter
    - openssl aes-256-cbc -K $encrypted_799987a421b6_key -iv $encrypted_799987a421b6_iv 
      -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - if [ ! -d "flutter" ] ; then git clone https://github.com/flutter/flutter.git -b stable; fi;
    - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
    - gem install bundler && cd ios && bundle install && cd ..
    script:
    - flutter packages get
    - flutter pub run flutter_launcher_icons:main
    - flutter test
    - cd ios && bundle exec fastlane internal
    cache:
      cocoapods: true
      bundler: true
      directories:
      - "$HOME/.pub-cache"
      - "$HOME/flutter"
